lab10/lab/urls.py
from django.urls import path

from . import views

app_name = 'lab'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:id_>/', views.detail, name='detail'),
    path('add/', views.add, name='add'),
    path('remove/<int:id_>/', views.remove, name='remove'),
    path('update/<int:id_>/', views.update, name='update'),
]

lab10/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('lab/', include('lab.urls')),
    path('admin/', admin.site.urls),
]

lab10/lab/models.py
from django.db import models


class User(models.Model):
    login = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    access=models.IntegerField(default=0)

class Citizen(models.Model):
    name = models.CharField(max_length=200)
    age=models.IntegerField(default=0)
    place_reg = models.CharField(max_length=200)

lab10/lab/forms.py
from django import forms
from .models import Citizen


class Form(forms.ModelForm):

    class Meta:
        model=Citizen
        fields=(
            'name','age','place_reg'
            )

lab10/lab/views.py
from django.shortcuts import render
from .models import Citizen
from .forms import *

def index(request):
    citizens = Citizen.objects.all()
    return render(request, 'lab/index.html', {'citizens': citizens})

def detail(request, id_):
    citizens = Citizen.objects.get(pk=id_)
    return render(request, 'lab/detail.html', {'citizens': citizens})

def add(request):
    form=Form(request.POST or None)
    if request.method=='GET':
        context= {'form':form}
        return render(request,'lab/add.html',context)
    else:      
        if form.is_valid():
            form.save()
            citizens = Citizen.objects.all()
            return render(request, 'lab/index.html', {'citizens': citizens})
        else:
            return render(request,'lab/add.html',{'form':form})

def update(request, id_):
    form=Form(request.POST or None,instance=Citizen.objects.get(pk=id_))
    if request.method=='GET':
        return render(request,'lab/update.html',{'form':form,'citizen':Citizen.objects.get(pk=id_)})
    else:      
        if form.is_valid():
            form.save()
            citizens = Citizen.objects.all()
            return render(request, 'lab/index.html', {'citizens': citizens})
        else:
            return render(request,'lab/update.html',{'form':form,'citizen':Citizen.objects.get(pk=id_)})


def remove(request, id_):
    citizens = Citizen.objects.get(pk=id_)
    citizens.delete()
    citizens = Citizen.objects.all()
    return render(request, 'lab/index.html', {'citizens': citizens})

lab10/mysite/views.py
from django.shortcuts import render
from lab.models import Citizen


def index(request):
    citizens = Citizen.objects.all()
    return render(request, 'lab/index.html', {'citizens': citizens})

lab10/lab/templates/lab/add.html
<form action="{% url 'lab:add' %}" method="post">
        {% csrf_token %}
	<table>
        {{form}}
        </table>
<input type="submit" value="Add"/>
<a href="{% url 'lab:index'%}">Back</a>

lab10/lab/templates/lab/detail.html
Citizen
{% if citizens%}
<ul>
        Name: {{ citizens.name }}<br> Age: {{ citizens.age }} <br> Place of Reg: {{citizens.place_reg }} <br> ---
<a href="{% url 'lab:remove' citizens.id %}">Remove </a> <br>---
<a href="{% url 'lab:update' citizens.id %}">Update </a> 
</ul>
{% else %}
    <p>No Citizens are available.</p>
{% endif %}
<a href="{% url 'lab:index'%}">Back</a>

lab10/lab/templates/lab/index.html
Citizens 
{% if citizens%}
    <ul>
    {% for c in citizens %}
        <li><a href="{% url 'lab:detail' c.id %}">Name: {{ c.name }} </a> ---
<a href="{% url 'lab:remove' c.id %}">Remove </a> ---
<a href="{% url 'lab:update' c.id %}">Update </a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Citizens are available.</p>
{% endif %}
<a href="{% url 'lab:add'%}">Add</a>

lab10/lab/templates/lab/update.html
{% if citizen%}
<form action="{% url 'lab:update' citizen.id %}" method="post">
        {% csrf_token %}
	<table>
        {{form}}
        </table>
<input type="submit" value="Update"/>
<a href="{% url 'lab:index'%}">Back</a>
{% endif %}